### ISSUE TITLE
Rules disappear after Cancel All

### ISSUE THREAD

**Issue by TheAxelander** [TheAxelander/OpenBudgeteer#102]
Steps to reproduce:

* Open Rules
* Click on Edit all
* Click on Cancel all
* All rules disappeared

**Comment by KiwiKid** [comment]
This may or may not be the same issue, i found that rules were being created with a TargetBucketId of 0 and (i believe) locking up the UI. i found running:
```
delete from BucketRuleSet WHERE TargetBucketId = 0;
```
removes the bad rule sets and fixes the issue - Not sure if helpful!

**Comment by KiwiKid** [comment]
I think it has something to do with having it open on multiple tabs - don't seem to get it when i stay on one window, hmm

**Comment by TheAxelander** [comment]
Working in multiple tabs shouldn't be the issue as this was happening for me in single tab. I think there is just on overall refresh of the page missing once you cancel the mass edit function. If you reload the page on your own everything should be fine.

**Comment by TheAxelander** [comment]
Fixed on `pre-release`
