### ISSUE TITLE
Nordigen integration 

### ISSUE THREAD

**Issue by kekonn** [TheAxelander/OpenBudgeteer#103]
Nordigen is a company that provides a free gateway to PSD2. This will allow to extract data from almost any official European bank through a single API.

I am already working on this on my fork, but wanted to make an issue to track this progress.

**Comment by TheAxelander** [comment]
Nice, looking forward to that. Thanks a lot already for your efforts on it

**Comment by kekonn** [comment]
I might need some help integrating it in the front end if time comes. I am new to Blazor.

I will also be adding some abstractions so that parts can be reused again for similar integrations.

**Comment by TheAxelander** [comment]
Feel free to concentrate on the backend, I can then take care integrating it to Blazor.

**Comment by kekonn** [comment]
I will have to do some frontend for testing, since unit testing a service that relies entirely on third party responses is not really useful, but it will definitely need another pass on the front end part before it's ready. I have theoretically built the first part of the back end and am now working on the ui part to test that.

Purposes of the first part is to allow selecting the bank account to sync (or creating that connection if it doesn't exist yet).

These services are heavily rate limited though (only four checks for transactions allowed per day or something), so I'm also experimenting with caching for certain requests.

The idea is that aside from file import, there is a cloud import screen. Here the user can select a bank service (if any is detected) and after that a supported bank etc. Nordigen will allow us to connect to any bank that supports PSD2, but perhaps the same classes and ways of working will work for other banks that provide APIs.
