### ISSUE TITLE
Tried to create a new rule, now all rules went missing from GUI

### ISSUE THREAD

**Issue by charyouz** [TheAxelander/OpenBudgeteer#104]
Tried to create a new rule with amount -XXX.XX, clicked on the checkmark to save and then all rules disappeared from GUI

Reloaded page and all have disappeared. After going to Rules page, cannot leave page anymore and no buttons work, so cannot create new rules, cannot go to other pages.

All other pages work fine, if I go to them directly.

Version 1.5.2

**Comment by TheAxelander** [comment]
Looks like that your latest rule is causing a crash on the Rules page. To resolve this you would need to delete that rule directly from the database.

Of course I'm also interested to know why this happened to prevent such situations in future. Would be great if you could share your input from that rule to me so I can have look on it and reproduce it on my side

**Comment by charyouz** [comment]
Now finally got around to pulling out the database from my docker container.
I noticed that this is closed, but still thought to put it here just in case

Here is the data from sqlite3 database MappingRule table (hope it's the correct one):
1|1|4|1|231
3|3|2|3|TEXT
5|5|4|1|200
6|4|4|1|-2.8
7|6|4|1|-360.32

**Comment by charyouz** [comment]
@TheAxelander adding to this, deleted the last one line (that broke the whole thing), did not fix issue...

could the issue be in "BucketRuleSet" table:

1|0|herp10
3|0|derp|1
4|0|lerp|18
5|0|even more text|35
6|0|that is private|0

I noticed that the last TargetBucketId is 0, so would that cause the issue?

**Comment by TheAxelander** [comment]
>I noticed that the last TargetBucketId is 0, so would that cause the issue?

Potentially yes I would say. As there is some database rework coming for 1.7 I expect that will no longer happen in future (hopefully).
