### ISSUE TITLE
Error on saving import profile

### ISSUE THREAD

**Issue by bas-rik** [TheAxelander/OpenBudgeteer#121]
I,ve installend openbudgeteer via docker-compose the site is running fine, I kan make an account, buckets and transactions.
When i try to do an import i get an error: `Unable to save Import Profile: Sequence contains no elements`

How can I fix it. 

The next step stays disabled

**Comment by TheAxelander** [comment]
Can you please share your input from the first step, maybe then I'm able to reproduce it on my side to see what's wrong here.

**Comment by bas-rik** [comment]
Here is the file i've tryed:
[Knab transactieoverzicht  betaalrekening - 2022-12-11 - 2023-01-11.csv](https://github.com/TheAxelander/OpenBudgeteer/files/10390700/Knab.transactieoverzicht.betaalrekening.-.2022-12-11.-.2023-01-11.csv)

**Comment by TheAxelander** [comment]
I see, something on the Column mapping is not working correctly. I also had some issues with resetting selections (created another issue for that #122). 

I will have a more deeper look into that and try to fix it on short notice.

**Comment by TheAxelander** [comment]
Should be now fixed with update `1.6.2`

**Comment by bas-rik** [comment]
It works well now. That was fast!

Maybe put the button for creating and saving the profil in the 3 step? Saving was possible when completng the 3th step.

**Comment by TheAxelander** [comment]
Good point, I overall plan to improve this handling (see #124) then I can also think about what's the best place to put these buttons, especially if a new Profile is created
