### ISSUE TITLE
API to insert transactions?

### ISSUE THREAD

**Issue by TommySharpNZ** [TheAxelander/OpenBudgeteer#127]
I would like to add transactions using a rest api... Is this possible?

**Comment by TheAxelander** [comment]
I think it's possible, so far I have not yet considered an API for OpenBudgeteer. But it would take some time for me as I'm not really experienced in developing and documenting proper APIs. Nevertheless I add this one in my overall backlog.

**Comment by csillaggyujto** [comment]
Hi guys! Please monitor #140 for progress.
