### ISSUE TITLE
Import value can't be converted 

### ISSUE THREAD

**Issue by Cliff-R-K** [TheAxelander/OpenBudgeteer#132]
When I try the import function I get the error Value can't be converted for values like "-123.4" is this a bug ?

Example:

<html>
<body>

10 | Column 10 with Value '-135.00' cannot be converted10\|81934\|9943966010\|"Privatkonto"\|SEK\|2023-02-20\|2023-02-20\|2023-02-20\|"GOOGLE *Google P"\|"GOOGLE *Google P"\|-135.00\|1066.76
-- | --

</body>
</html>

**Comment by TheAxelander** [comment]
Which language tag did you used for the number format?

**Comment by Cliff-R-K** [comment]
sv-SE

**Comment by TheAxelander** [comment]
With this language tag the number format would look like `1 234,56`, that's the reason why it doesn't work. Try a different one which corresponds to the number format in you file. I think `en-US` might work here.
