### ISSUE TITLE
Docker sqlite not working

### ISSUE THREAD

**Issue by crashcoq** [TheAxelander/OpenBudgeteer#135]
Hello

I use docker with sqlite but not work.
And it create two ports, 443/tcp  and 6100-> 80 tcp
how works?

**Comment by TheAxelander** [comment]
Can you please share your Docker Compose or Docker run command and a bit more details what exactly doesn't work.

**Comment by crashcoq** [comment]
I use this command 

Docker run -d --name='openbudgeteer' -e 'CONNECTION_PROVIDER'=sqlite -v /srv/dev-disk-by-label-NEXTCLOUD/actual_server:/app/database -p 5007:443 -p 5008:80 axelander/openbudgeteer:latest


Docker container ls -a                                                                CONTAINER ID   IMAGE                            COMMAND                  CREATED              STATUS              PORTS                                         NAMES
0a8f9078d78d   axelander/openbudgeteer:latest   "dotnet OpenBudgetee…"   About a minute ago   Up About a minute   0.0.0.0:5008->80/tcp, 0.0.0.0:5007->443/tcp   openbudgeteer

**Comment by TheAxelander** [comment]
Overall `-p 5007:443` is not necessary, only `-p 5008:80` would be relevant. On first glance the command looks fine. Can you see if the database file has been created in `/srv/dev-disk-by-label-NEXTCLOUD/actual_server`? What's in the logs for the container?

**Comment by crashcoq** [comment]
I have tested without `-p 5007:443` same problem. 
On '/srv/dev-disk-by-label-NEXTCLOUD/actual_server/' , I have the database created by openbudgeted

**Comment by TheAxelander** [comment]
So what is the exact issue? Does the page not load? What about the docker logs?

**Comment by crashcoq** [comment]
Indeed nothing is displayed, no web page
how to enable logging?
![Capture d’écran du 2023-03-13 22-49-14](https://user-images.githubusercontent.com/8464834/224840094-73d87f00-4267-43a3-a1e4-98111c245bb8.png)

**Comment by TheAxelander** [comment]
I used the same docker run command (just adapted the volume part) and it's working fine. Can you maybe try to use another path where you store the database. Otherwise I have no clue as everything looks fine from what I can see and I'm not able to reproduce the issue on my side.
![image](https://user-images.githubusercontent.com/17849665/224849691-41b6fcfe-d807-4051-89ab-53f0151ed3ea.png)

**Comment by crashcoq** [comment]
With store the database in /tmp, it's OK
Otherwise any web page

**Comment by TheAxelander** [comment]
So am I correct that the issue is resolved?

**Comment by crashcoq** [comment]
Yes resolved
