### ISSUE TITLE
[Refactor] Move data access code to repository

### ISSUE THREAD

**Issue by csillaggyujto** [TheAxelander/OpenBudgeteer#139]
Apply the repository pattern to remove data access code from viewmodels and the dbcontext class

**Comment by TheAxelander** [comment]
So what would be the benefit on that for MVVM? To be honest I'm not familiar with the repository pattern.

**Comment by csillaggyujto** [comment]
This is something I would like to do myself after the postgres integration.
The repository pattern basically separates the data tier (queries) from both the ViewModel and the DataContext. This makes the DataContext clean for code generation, and to explore the database structure for further development. This will also make the ViewModel clean, since it will not depend on a specific implementation of the database so you can test it against a mock data tier. (With the assumption that the following data is available... When I... Then I expect... stories)

**Comment by TheAxelander** [comment]
Interesting, looking forward to see how this concept will interact with MVVM. 
You are right for mock data I somehow found a way how to do it, but I'm pretty sure there are better ways on that, so let's see :)

**Comment by csillaggyujto** [comment]
The task is VIP as part of #140.
As of how it interacts with MVVM:
I try to define the API by the methods currently used by the view model layer to access the database directly. Db entities are also replaced by DTOs. The system will bevdependent on a service layer, which can have direct database access (desktop/monilithic paradigm) or communicatie through an api (microservices paradigm)
