### ISSUE TITLE
[Refactor] Async support

### ISSUE THREAD

**Issue by csillaggyujto** [TheAxelander/OpenBudgeteer#145]
Database operations - being IO - are asynchronous by design.  Currently ViewModels use with the await Task.Run pattern more suited for CPU-bound background work. Refactoring is needed so that Async is used properly wherever needed.

**Comment by csillaggyujto** [comment]
The task is work in progress as part of #140

**Comment by Anu6is** [comment]
@csillaggyujto have you given up on making modifications to this project? Looking at your fork there seemed to be some worthwhile changes in progress

**Comment by csillaggyujto** [comment]
@Anu6is unfortunately I wasn't able to allocate enough time to complete my refactor before @TheAxelander committed his.
