### ISSUE TITLE
[CR] Multi-currency support

### ISSUE THREAD

**Issue by csillaggyujto** [TheAxelander/OpenBudgeteer#146]
Some people has to deal with transactions in multiple currencies (living in east europe working for a Western corporation, I get my salary in EUR, and when I buy stuff online, I sometimes pay in EUR, GBP and USD. As well as transactions in the ... something trying to be sold as currency by the local "government". Other people may invest in Forex, crypto or stocks. Other people still may deal with fintechs giving them the ability to use multi-currency accounts, or just want to know exactly how much that tasty pálinka actually cost them the last time they were in Budapest...) Many other budgeting software can handle multiple currencies, but they are not as easy to use or intuitive as OpenBudgeteer. So my idea is:

- The system has a native currency which is used as a baseline
- Since buckets are the base of the system, buckets should display as the baseline currency
- Accounts may have a currency
- On your bank statement, the transaction will be displayed in the account currency, and the actual currency, so transactions will have original and account currency record. Transactions input in the account currency will have the original currency greyed and filled out.
- Since you need to bucket every transaction, you need to know the FX rate at transaction input time, so that your buckets get drawn on accordingly.
- Open data sources could be used to automatically get the day's forex (crypto, stock...) rates

Essentially, I'm looking at something like porting the multi-currency functionality similar to GNU Cash, while still keeping the user friendly features of OpenBudgeteer.

**Comment by TheAxelander** [comment]
Something I really need to think about like what kind of side affects might occur, rounding errors, changing conditions on 3rd sources. The basic idea at the very beginning was that the currency is just a "display thing" and the focus is more on keeping calculations and balancing buckets clean.

Of course I'm open for any kind of proposal and experimentation, I'm just expressing my concern here.
