### ISSUE TITLE
[CR] Automation testing

### ISSUE THREAD

**Issue by csillaggyujto** [TheAxelander/OpenBudgeteer#147]
I'm not that much of a test automation engineer, but since we're in docker/k8s, and starting to have reproducible environments, and builds, maybe someone could be kind enough to write some tests (integration/e2e) so that regression would be easier?

**Comment by TheAxelander** [comment]
So there are already some unit tests available that should try to ensure, that the core calculations are still functional for every build. What is of course missing are things like writing UI tests where I don't have any experience in.
