### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by DastardlyDino** [TheAxelander/OpenBudgeteer#153]
I'm feeling dump and don't know where to put a feature request so I'm putting this here so someone can point me in the right direction. Is exporting to CSV somewhere on the roadmap?

**Comment by TheAxelander** [comment]
All good, it's the right place to put such kind of request.

So far I have not considered any kind of export functionality. May I ask what is the use case of exporting the data to CSV so that I have a better understanding on what is to be expected.

**Comment by csillaggyujto** [comment]
With EP Plus (4 or below, however we do qualify for the non-commercial license), we will get free Excel (xls and/or xlsx) export as well as CSV, However your use case would still be appreciated @DastardlyDino so that we can decide how to help you the best.
