### ISSUE TITLE
[pre-release] Account Page: Display transactions failed

### ISSUE THREAD

**Issue by TheAxelander** [TheAxelander/OpenBudgeteer#159]
Happens on my QA environment 

![image](https://github.com/TheAxelander/OpenBudgeteer/assets/17849665/cde9b557-e661-4701-aa6b-c7fdbaaa04e3)

**Comment by Lucaber** [comment]
found the issue here when an account has less than 100 transactions: https://github.com/TheAxelander/OpenBudgeteer/commit/4670b08d03cd255f1a04ae362e336cbd3842e1f0#diff-f6d582a2aac50834322b6f981e1b557285982313b9d28dd7ace225c0f7dc870cR244-L263

**Comment by TheAxelander** [comment]
Damn, didn't expected that `GetRange` just fails if there are less than 100 transactions. I thought LINQ will be then translated into something like `SELECT TOP 100`. The right function would be `Take(100)` here.

Thanks a lot for that.
