### ISSUE TITLE
[HELP] Buckets wont work automatically

### ISSUE THREAD

**Issue by Serph91P** [TheAxelander/OpenBudgeteer#162]
Hi,

Imported all my data and wanted to Setup some Buckets. But Rules and I guess how automatic setup works wont do anything?
Setup a rule to set my salary as income. It does nothing where can I check if there is an error or something.  It is written in den Readme that buckets should be positive? If I want to see how much I spend on food or rent how would that be positive? Like rent is a monthly expense which will never be positive :D  

Seems like I dont Understand this application :D

**Comment by TheAxelander** [comment]
Hi, so first of all the usage of rules is not mandatory, it's just a way to automate the assignment of transactions to a certain bucket. On Transaction Page there is a button called "Propose Buckets" where the defined rules will be applied.

All in all I currently work on a more detailed "Get Started" guide to better understand how everything works. In short for you, as you have already imported some transactions, you can now create some Buckets on the Bucket Page to structure your expected expenses (I would start with simple buckets to get familiar with the system). 
After that you put some money into these buckets, depending on how much you expect for them.
Then go back to Transaction Page and assign your transactions to the respective bucket.
If you would now go back to Bucket Page you will see how good your estimation was. It's important that the bucket balance is never negative (in case just put some additional money into it)

OpenBudgeteer is based on the Bucket Budgeting Principle, there are various sites which explain this methodology in a more detailed way.

Hope this helps to get started, let me know in case there anything else.
