### ISSUE TITLE
Transactions between accounts

### ISSUE THREAD

**Issue by shugyosha89** [TheAxelander/OpenBudgeteer#164]
Maybe this feature is present and I just can't find it, but it seems like a common use case to transfer money between accounts. For example one bank account to another.

I couldn't find an easy way to do this. It looks like you need to create two transactions, one for each account.

Is there a way to transfer money between accounts that I'm missing?

**Comment by TheAxelander** [comment]
To transfer money from one account to another can be done by creating two transactions, one outbound from the sending account and one inbound from the receiving account. Both transactions should be then assigned to the Bucket `Transfer`, this ensures that some statistic calculations are correct, e.g. Total Income.
