### ISSUE TITLE
Entering transactions with a date prior to database creation - buckets not available

### ISSUE THREAD

**Issue by Bucket1616** [TheAxelander/OpenBudgeteer#174]
Installed and created the initial database yesterday.  Created buckets without modifying first target date.  Entered transactions with dates  prior to installation date and no buckets are available for selection.  This seems not desirable.

**Comment by Bucket1616** [comment]
In attempting to diagnose, I re-created a bucket with a new, earlier first target date and now it appears for selection in a early dated transaction.

**Comment by TheAxelander** [comment]
The Bucket gets a Valid from date in respective Month where it was created. Hence it is not available in previous months
