### ISSUE TITLE
Consider making top row of buttons more compact

### ISSUE THREAD

**Issue by Bucket1616** [TheAxelander/OpenBudgeteer#175]
When the top row of buttons has to over-run onto a second line within a browser, those menu items cover the buttons in the lower pane of the window.  I would expect that this could be re-created by making a browser window more narrow and seeing that the menu buttons overlap the transaction entering buttons.

**Comment by TheAxelander** [comment]
That's true, the Navigation is not that responsive so that the content below re-aligns correctly. Could be something to improve in future.

**Comment by TheAxelander** [comment]
Consider moving the navigation to the right as expandable container, similar to paperless-ngx.

**Comment by TheAxelander** [comment]
Available in `pre-release`
