### ISSUE TITLE
Can't access the app

### ISSUE THREAD

**Issue by mariomaz87** [TheAxelander/OpenBudgeteer#183]
Hi, I want to try the app but I think I'm missing something.
I'm running on a Raspberry Pi4 and trying the docker installation. I pulled the image with "docker pull axelander/openbudgeteer" and then run the image with "sudo docker run -d --name='openbudgeteer'     -e 'Connection:Provider'='sqlite'     -v '/home/mario/openbudget:/app/database'       'axelander/openbudgeteer:latest'". I removed the -p since I don't need to specify a different port. How am I supposed to access the app then? The docker is running.
I tried to open a browser from a Linux pc on my local lan and accessing my Raspberry at port 80 but it does not load. I also tried to specify a different port but it still won't load. Am I missing somethings? Thanks!

**Comment by TheAxelander** [comment]
Can you please share the docker logs. Maybe there is already the reason mentioned

**Comment by TheAxelander** [comment]
Btw: You need to use `-e 'CONNECTION_PROVIDER'='sqlite'`

May I know where you checked the details where `-e 'Connection:Provider'='sqlite'` was still mentioned as parameter?

**Comment by mariomaz87** [comment]
Thanks for the feedback. I found the parameter mentioned in the Docker Hub: https://hub.docker.com/r/axelander/openbudgeteer#!
I tried with the -e 'CONNECTION_PROVIDER'='sqlite' and the log is this:

warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {2ebffb7e-f4d8-4cdb-a8c2-75c2bbdbe038} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app

Maybe there is an issue with the ip it's listening on?

**Comment by TheAxelander** [comment]
Thanks for the hint to Docker Hub, then I know where I still have to fix the documentation.

The log is looking good (ignore the warnings). It should now run.

Overall for documentation please check https://theaxelander.github.io

**Comment by mariomaz87** [comment]
I still can't access the app if I go to myraspip:80 with a browser. Is there another way to access it? I can't find it in the documentation, thanks!

**Comment by TheAxelander** [comment]
Did you tried to set another Port? Can you also share your latest `docker run` command so I can check it on my side too

**Comment by mariomaz87** [comment]
Thanks. I'm trying with "sudo docker run -d --name='openbudgeteer' -e 'CONNECTION_PROVIDER'='sqlite' -v '/home/mario/openbudget:/app/database' 'axelander/openbudgeteer:latest' -p '6100:80/tcp'". I then tried to access it both on port 6100 and 80 with no results. The log is still saying that it's listening on port 80.

**Comment by TheAxelander** [comment]
This issue is that your `-p` part is at the end of the command and not recognized by the `docker run` command.

Please try to run `sudo docker run -d --name='openbudgeteer' -e 'CONNECTION_PROVIDER'='sqlite' -v '/home/mario/openbudget:/app/database' -p '6100:80/tcp' 'axelander/openbudgeteer:latest'`

**Comment by mariomaz87** [comment]
It worksss! Thanks! The only things is that the log states at it's listening on port 80, while I can access the app only on port 6100.

**Comment by TheAxelander** [comment]
The logs will always tell port 80 as it is the default port for the Container.
