### ISSUE TITLE
Consistency when displaying amounts

### ISSUE THREAD

**Issue by nowizh** [TheAxelander/OpenBudgeteer#188]
**Describe the solution you'd like**
It would be nice to see comma separators and monetary units when amounts are displayed in the transaction view, like the statistical values in the bucket view.
And it would also be nice to see the currency denomination in the balances of individual buckets in the bucket view.

**Comment by TheAxelander** [comment]
Adding the currency for all amount values could be indeed something. I'm not sure what you mean with comma separators, as they are displayed everywhere.

**Comment by nowizh** [comment]
Not sure what's gone wrong. But in my transaction view, I can't see comma separators on amounts.
![image](https://github.com/TheAxelander/OpenBudgeteer/assets/32785613/b972f0f9-22a3-4a4d-81bf-4aecf3079081)

Hey, and so much thanks to you @TheAxelander for this wonderful project!

**Comment by TheAxelander** [comment]
Thanks a lot for your feedback, really appreciated.

Based on your screenshot I now got your point. The format settings for things like date, numbers and currency are based from the `APPSETTINGS_CULTURE`. In your case the settings that you have set uses a `.` instead of a `,`.

Or do you mean a  "1000" separator, so in your case like `-33,700.00`?

**Comment by nowizh** [comment]
I mean the "1000" separator. In bucket view it's showing like "12,300.00" or "-8,900.00"; and with currency denomination (like in stats on the top of the bucket view) it's like "-₩1,000,000", or "₩6,000,000".

Here's bucket view screenshot:
![image](https://github.com/TheAxelander/OpenBudgeteer/assets/32785613/3bd2c2bb-5ac2-4dc1-aedd-1b13aa491bf8)

It's just not consistent. I want to see amounts with the same "-₩1,000,000" format everywhere. (currency + 1000s sep.)

And in my currency, there's extremely little use-cases for amounts below 1. So, it's also good to have options for number of digits after the decimal point. Possibly I can open another issue :)

**Comment by TheAxelander** [comment]
Got it, thanks for clarification. I didn't noticed that it was missing on the Transaction View.

Based on your screenshot I also see that such huge number lead to some misalignment, which I will also rework as part of #189.
