### ISSUE TITLE
change currency

### ISSUE THREAD

**Issue by supamartin** [TheAxelander/OpenBudgeteer#197]
In V1.8 neither the documentation, nor the app has any hint of how to change the currency.

**Comment by TheAxelander** [comment]
The currency is defined based on `APPSETTINGS_CULTURE`. As an example if you use `en-US` it uses `$`, for `de-DE` it uses `€`

**Comment by supamartin** [comment]
Got it, thank you!
Would be nice to find this information in the documentation. I think it’s important for most of us.

**Comment by TheAxelander** [comment]
There is a notice in the documentation regarding currency, number and date format. It's also accessible via search function.
