### ISSUE TITLE
How can I make an account system?

### ISSUE THREAD

**Issue by EtherForge** [TheAxelander/OpenBudgeteer#213]
If I host this site among my friends, how can I create a login/registration window and, accordingly, get into my personal, not shared, account?

**Comment by TheAxelander** [comment]
You could run one docker container of OpenBudgeteer per user. For Login screen I would propose using something like [Authelia](https://github.com/authelia/authelia) in combination with a supported reverse proxy.

Overall I would not recommend hosting financial data publicly available in the internet (even with any kind of login screen) unless you really know what you do (server security, encryption, system hardening etc.)

**Comment by EtherForge** [comment]
Sorry, if it's not difficult, you can attach instructions for linking for the creating docker containers, Authelia and OpenBudgeteer? I don't really know how to tie it all together to work properly.

**Comment by TheAxelander** [comment]
Linking the containers will be not sufficient as you need to configure and setup the various containers, especially Authelia and the reverse proxy. Plus you need to understand the concept how all of that works.

In a step by step approach I would propose to get familiar with a reverse proxy first. Once you have successfully set this up, you can then extend this setup with Authelia.
