### ISSUE TITLE
docker compose for latest release

### ISSUE THREAD

**Issue by slfhstr** [TheAxelander/OpenBudgeteer#218]
Nice app.

The docker-compose examples provided reference an image `openbudgeteer:prerelease`
But the latest release is 1.7

Is it just a question of changing image name to e.g. `openbudgeteer:latest` ?
I ask because I notice that there have been some changes to environment labels.  
And the app states Postgres version has been significantly changed. 
I don't want to guess at changes to services configuration.

It would be very helpful to update the example docker-compose files and also the documentation.

**Comment by TheAxelander** [comment]
The `pre-release` tag is set in the repository example files and README as it refers to the default branch. 
But in the documentation you will see the right tags (or none, as `latest` is the default Docker tag). Alternatively you can also use a specific version tag (e.g. `1.7.1`), all details are available on Docker Hub and the documentation.
Changes at service configuration I usually announce quite early as Breaking Changes (like I did for the changes from 1.6 to 1.7) and first insights you can find in the pre-release documentation

**Comment by slfhstr** [comment]
Fair enough.
Although a tad odd IMO that README reflects a pre-release rather than the current stable.

**Comment by TheAxelander** [comment]
To be honest I was in the past already thinking about to change this in the README to make it a little bit more clearer what alternative tags are available. 
Let me follow up on that later...
