### ISSUE TITLE
Data Consistency in 1.7 freezes the page

### ISSUE THREAD

**Issue by slfhstr** [TheAxelander/OpenBudgeteer#219]
Data Consistency in 1.7 freezes the page

**To Reproduce**
Run up 1.7 in docker compose using sqlite
Click on Data Consistency

**Expected behavior**
Err, don't know as can't see what should be intended
At least the page should load

**Additional helpful details**
 - 1.7
 - SQLITE
 - docker compose
 - linux vps
 - safari

**Comment by slfhstr** [comment]
Tried it again with 1.7 and Postgres and it works

**Comment by TheAxelander** [comment]
Depending on the database size it takes a few moments once all checks have been executed. Did you noticed any messages from Docker logs?

**Comment by Bucket1616** [comment]
I get the same issue with sqllite.  Never returns from Data Consistency Check, also data did not make the ->1.7 migration.

**Comment by TheAxelander** [comment]
Look like a return of issue #57. Can you please check if you can see a similar error message in the logs?

**Comment by TheAxelander** [comment]
Seems to be fixed with recent changes for Update 1.8, hence closing this.
