### ISSUE TITLE
[pre-release] Unable to select Recurrence Type in Manage Recurring Transactions Dialog

### ISSUE THREAD

**Issue by TheAxelander** [TheAxelander/OpenBudgeteer#225]
**Describe the bug**
Selecting a Recurrence Type in Manage Recurring Transactions Dialog is always being reset

**To Reproduce**
1. Go to Transaction Page
2. Go to `Manage` on `Recurring Transaction`
3. Click on `Create Transaction`
4. Select any `Recurrence Type`

**Expected behavior**
Selected item is shown.

**Comment by Lucaber** [comment]
Creating a rule has probably the same issue.

**Comment by TheAxelander** [comment]
That's correct, I need to apply this fix on other places too.
