### ISSUE TITLE
Drop SQLite support

### ISSUE THREAD

**Issue by TheAxelander** [TheAxelander/OpenBudgeteer#239]
Due to recurrent issues with SQLite (#238 #233 #221 #219 #57) I'm ~~thinking about~~ dropping overall SQLite support and ~~maybe~~ also concentrating on stabilizing one database provider due to efforts in regression tests and updating container dependencies.

- [x] Cleanup coding
- [x] Rewrite Unit Test
- [x] Check Github Actions
- [x] Update documentation
- [x] Check Unraid template

**Comment by mattyvau** [comment]
SQLite is still referenced in a few places in the documentation. Not sure if the remaining ones are intended, so just pointing them out.
I found:
https://theaxelander.github.io/latest/config/#database << in the line about automated database initialisation
https://theaxelander.github.io/latest/install/#build-and-deploy << where appsettings.json is referenced

**Comment by TheAxelander** [comment]
Thanks for the hint, I fixed it
