### ISSUE TITLE
Date of Bucket Movements always on the first of the month

### ISSUE THREAD

**Issue by Lucaber** [TheAxelander/OpenBudgeteer#240]
Hi, is there a reason that bucket movements are always saves with the date of the first in the current month?

https://github.com/TheAxelander/OpenBudgeteer/blob/pre-release/OpenBudgeteer.Core/ViewModels/EntityViewModels/BucketViewModel.cs#L703
https://github.com/TheAxelander/OpenBudgeteer/blob/pre-release/OpenBudgeteer.Core/ViewModels/EntityViewModels/BucketViewModel.cs#L229

**Comment by TheAxelander** [comment]
Yes and no. For calculations and display purposes I need to know in which month a Bucket Movement has happend, the day is not really needed. Instead of using two specific properties/db columns I decided to stick to a Date and just defaulted the day to 1.

**Comment by Lucaber** [comment]
Then setting the current date shouldn't be a problem? I'm asking because the date ist also shown in the transaction history of a bucket and is ordered accordingly to the beginning of a month.

**Comment by TheAxelander** [comment]
Well yes, that would be the only impact
