### ISSUE TITLE
Missing Import Profile Save Button

### ISSUE THREAD

**Issue by Not-Simix** [TheAxelander/OpenBudgeteer#252]
Hi! When I am importing I am not seeing the "Save Profile" button for the import config, not sure if this is due to my docker compose or not.
![Openbudgeteer Issue](https://github.com/TheAxelander/OpenBudgeteer/assets/124903630/759b3089-5b55-4168-b223-a65737c8578e)

This is the compose I am using

openbudgeteer:
    image: axelander/openbudgeteer:latest
    #image: axelander/openbudgeteer:pre-release
    #image: axelander/openbudgeteer:1.7
    container_name: openbudgeteer
    ports:
      - 3003:8080
    environment:
      - CONNECTION_PROVIDER=mariadb
      - CONNECTION_SERVER=localhost
      - CONNECTION_PORT=3306
      - CONNECTION_DATABASE=Openbudgeteer
      - CONNECTION_ROOT_PASSWORD=filler
      - CONNECTION_USER=filler
      - CONNECTION_PASSWORD=filler
      - APPSETTINGS_CULTURE=en-US
      - APPSETTINGS_THEME=morph
    depends_on:
      - mariadb
    labels:
      - wud.watch=true

  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: filler
    volumes:
      - ~/Mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    labels:
      - wud.watch=true

**Comment by TheAxelander** [comment]
Well there is nothing filled in, so that's why you can' t see any Save button. Or do you look for the "Import button"?

**Comment by Not-Simix** [comment]
Even with everything filled out I'm still not seeing a save button anywhere. Went through the full import config to make sure.
![Openbudgeteer Issue Cont](https://github.com/TheAxelander/OpenBudgeteer/assets/124903630/59b5177c-bf6d-4c27-aaab-660d5b83958e)

**Comment by TheAxelander** [comment]
Did you filled out the mapping section completely? As you can see that last step is still in status disabled

**Comment by Not-Simix** [comment]
Sorry, that was before I went through and double checked before sending. But yes, even with everything mapped and filled out I'm not seeing it. The save button should be in the Select Import Profile section right?

**Comment by Not-Simix** [comment]
![Openbudgeteer Issue Cont 2](https://github.com/TheAxelander/OpenBudgeteer/assets/124903630/46fc82bd-0e11-4649-b5ae-fe2a73d1eefb)
![Openbudgeteer Issue Cont 3](https://github.com/TheAxelander/OpenBudgeteer/assets/124903630/2851249f-b438-4bb5-b7fc-c05d42f219e5)
![Openbudgeteer Issue Cont 4](https://github.com/TheAxelander/OpenBudgeteer/assets/124903630/67f01342-35a2-4aac-820c-a76adae3d986)

Here are all 3 drop downs. Doing what I can to try and troubleshoot right now

**Comment by Not-Simix** [comment]
After continued clicking around it appeared. Apologies!

**Comment by TheAxelander** [comment]
No problem :)
