### ISSUE TITLE
V1.8.3: Bucket->Bucket Details lists full transaction amount, not the amount of the split going towards that bucket.

### ISSUE THREAD

**Issue by Bucket1616** [TheAxelander/OpenBudgeteer#256]
Recreation:

Create a transaction that is split between at least two buckets.

Go to the Buckets tab, find one of the two buckets used for the above transaction.  Click on the "Bucket Details" button.  The transaction created will appear under "Movements", showing the full amount of the transaction, not just the amount attributed to the one bucket.

Example:
Split Transaction:
![image](https://github.com/TheAxelander/OpenBudgeteer/assets/143653594/af00bad5-293d-40dd-9778-dfd174fb9f41)

Looking under the Gasoline Bucket Details:
<img width="880" alt="image" src="https://github.com/TheAxelander/OpenBudgeteer/assets/143653594/0049271b-288a-40ba-be81-6d38557e42ef">

The highlighted transaction appears showing an amount of -$338.43, which is the entire transaction amount, where I beileve it should only show -$28.05.

**Comment by TheAxelander** [comment]
Not a real bug as it only shows the referred Bank Transaction, but you are right it would make more sense to display the assigned amount only

**Comment by Bucket1616** [comment]
Thanks. Sounds like it is just showing the matching transactions.  As long as the numbers used to display the "Statistics" uses the splits instead of the total amount, definitely more of a feature or enhancement
