### ISSUE TITLE
V1.8.3: Transactions: Moving from July 2023 to August 2024 results in "Error during loading: Sequence contains no matching element" 

### ISSUE THREAD

**Issue by Bucket1616** [TheAxelander/OpenBudgeteer#258]
I was the trouble-maker who had challenges moving from Version 1.6.3 to latest.  There may be something in my data that is causing this.

Here is what is displayed:
![image](https://github.com/TheAxelander/OpenBudgeteer/assets/143653594/2bcc0f15-5261-4005-a7c5-d28f6f9fd451)

Looking at the data, there are numerous entries from this month that should be displaying.

Here are some of those transactions:
![image](https://github.com/TheAxelander/OpenBudgeteer/assets/143653594/1f6cd7cd-a190-490e-8c68-0af357251420)

Any ideas where to look to see if this is as a result of soemthing in my data?

Mike

**Comment by TheAxelander** [comment]
Hard to tell, seems like an unexpected data constellation. I would guess there is something wrong on the Bucket assignment. Can you see some relations of these Bank Transactions in table `BudgetedTransaction`?

**Comment by kapdap** [comment]
I was able to fix this after changing the ValidFrom fields in the BucketVersion table to an earlier date

**Comment by kapdap** [comment]
Changing Bucket.ValidFrom dates to an earlier time seems to fix this. May need to update BucketVersion.ValidFrom as well.

**Comment by Bucket1616** [comment]
Thanks, found the offending entry and was able to get this all back up and running!
