### ISSUE TITLE
Help for import

### ISSUE THREAD

**Issue by bckthomas** [TheAxelander/OpenBudgeteer#266]
Hi
I have an error when importing the date.
I've tried these formats without success: 
dd/MM/yyyy
d/m/y

Can you help me ?
Thanks

Log : 
Column 0 with Value '"28/09/2024"' cannot be converted
"28/09/2024"|"28/09/2024"|"CARTE 27/09 TICKET WEEZEVENT DIJON"|"27,99"|""

**Comment by TheAxelander** [comment]
Looking on the error message, could it be possible that you missed to add the `"` as Text qualifier in Step 2?

**Comment by bckthomas** [comment]
Quite simply
Sorry for my mistake

**Comment by TheAxelander** [comment]
All good, no problem :)
