### ISSUE TITLE
Import Page does not open correctly

### ISSUE THREAD

**Issue by Bucket1616** [TheAxelander/OpenBudgeteer#268]
**Describe the bug**
When clicking on the "Import" link on the left menu, I am presented with an error message about a missing column

**To Reproduce**
Go to the root page of the OpenBudgeteer Installation.  On the left menu, click "Import"

**Expected behavior**
No error.

**Screenshots**
![image](https://github.com/user-attachments/assets/c2bb5751-1ea6-471a-bc4a-4e6f8711544e)

**Additional helpful details**
 - Version: 1.8.3
 - Database MySql

Also, of note, I had the issue with originally being on the prior database and had to go through some effort to bring my data into MySql.  Maybe some other piece of information is missing in my database?

**Comment by Bucket1616** [comment]
Dug into this some more:  

Here is what my ImportProfile Table looks like:
![image](https://github.com/user-attachments/assets/4095792c-dece-41b5-8dbf-c181c2f01db2)

However, thee are no entries.  Not sure if that is okay

**Comment by TheAxelander** [comment]
The table is missing a column, the schema needs to look like this
![image](https://github.com/user-attachments/assets/4e20d501-41e0-48ba-b9d5-589760981a19)

**Comment by Bucket1616** [comment]
Thank you!  Added in that column and all is good!
