### ISSUE TITLE
Ability to type a few characters to search for the appropriate bucket?

### ISSUE THREAD

**Issue by Bucket1616** [TheAxelander/OpenBudgeteer#269]
**Describe the solution you'd like**
When entering transactions, it would be very helpful to be able to type a few characters like "dini" to find a bucket"Dining Out", for example.

**Additional context**
None

**Comment by TheAxelander** [comment]
This will be covered with #193

**Comment by Bucket1616** [comment]
Thanks, tried to search for this before posting, but must have missed it.
