### ISSUE TITLE
When the first bucket is selected for a transaction, use the transaction amount at the default bucket amount.

### ISSUE THREAD

**Issue by Bucket1616** [TheAxelander/OpenBudgeteer#270]
**Describe the solution you'd like**
It would be nice if when the first bucket is selected, if the entire amount of the transaction was entered as the bucket amount as the default.  While there are many times where an expense is a split between multiple buckets, most of the time, it is going to one bucket. It would be a huge time saver if, be default, the entire transaction amount went towards the first selected bucket amount.

**Additional context**
None

**Comment by TheAxelander** [comment]
Makes absolutely sense. I will consider this for the next release.

**Comment by Bucket1616** [comment]
Great, thanks for considering!

**Comment by tizzen33** [comment]
Hi. In addition to this, why not make the date of the transaction default to today instead of 1st of month?
