### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by tillcash** [TheAxelander/OpenBudgeteer#51]
I would like to run on a Raspberry Pi, but that would require ARM support. 
Add ARM builds for Docker image.

**Comment by Merlijnv** [comment]
same here for homeassistant on rpi4

**Comment by TheAxelander** [comment]
I have created an image which is available via axelander/openbudgeteer:arm64. I could only test this so far on my MacBook Air M1 but I think it should work on an rpi.

Will now try to automate this in Github Actions...

**Comment by TheAxelander** [comment]
Should be resolved with #60
