### ISSUE TITLE
Currency settings

### ISSUE THREAD

**Issue by 20repsej** [TheAxelander/OpenBudgeteer#52]
Settings to change what currency is displayed.

**Comment by apmillen** [comment]
Yes, I need GBP (£)

**Comment by faspina** [comment]
Can the currency be changed to USD ($)

**Comment by TheAxelander** [comment]
In `pre-release` there is now a new option in `appsettings.json` available which sets multiple things like Currency and Number format. It can be accessed via environmental variable `AppSettings:Culture`

Further details can be found [here](https://github.com/TheAxelander/OpenBudgeteer/tree/pre-release#additional-settings)
