### ISSUE TITLE
Change imported amount to negative

### ISSUE THREAD

**Issue by apmillen** [TheAxelander/OpenBudgeteer#53]
My bank provides 'Credit Amount' and 'Debit Amount' both as positive numbers, so there is no way for me to import my debit information.

Could there be separate column mappings for debit and credit and then an option to make debit amount into a negative number?

**Comment by TheAxelander** [comment]
`Pre-release` has now a new option on Import Page for the column mapping. If required a separate Credit column can be selected. In case the value is positive the amount will be automatically transformed into a negative number.
