### ISSUE TITLE
Creating a bucket group and clicking cancel crashes the application

### ISSUE THREAD

**Issue by Christoph-Wagner** [TheAxelander/OpenBudgeteer#56]
v1.4 in Debug mode, Windows, SQLite DB

1. Click "Create Bucket Group"
2. Click "Cancel"

Now my expectation would be for the group not to be created. Instead, only the modification is canceled before the button is properly saved, resulting in an NPE at `Bucket.razor` line 210: `@bucketGroup.BucketGroup.Name` as `bucketGroup.BucketGroup` is null. This makes the whole app unresponsive until the page is reloaded. The group is created anyway.

**Comment by TheAxelander** [comment]
Can confirm this. Will look into it.

**Comment by TheAxelander** [comment]
Should be resolved as part of #58
