### ISSUE TITLE
Install on Pi not possible due to not matching platform

### ISSUE THREAD

**Issue by Akashic101** [TheAxelander/OpenBudgeteer#62]
I wanted to install this app on my Pi 4B but ran during install into a problem. Using the command 
```
docker run -d --name='openbudgeteer' -e 'Connection:Provider'='sqlite'
-v '/data/openBugdeteer:/app/database' -p '6100:80/tcp'     'axelander/openbudgeteer:arm64'
```
results into the error-message
```
The requested image's platform (linux/arm64/v8) does not match the detected
host platform (linux/arm/v7) and no specific platform was requested
```
This problem persists when updating from Buster to Bullseye

**Comment by baldonharris** [comment]
Having the same problem.

**Comment by roupenig** [comment]
It looks like you have a 32 bit OS?
It's running fine on my Pi 4B Raspberry pi OS 64bit (Bullseye)

**Comment by Akashic101** [comment]
I'm indeed running the 32bit OS-version of bullseye. I will later try to upgrade to 64bit with another sd-card and see if it works then

**Comment by TheAxelander** [comment]
Was it possible for you to switch to 64bit OS and does it work? If yes I would then close this issue.

**Comment by Akashic101** [comment]
I'm sorry, I didn't had time to try it out yet. I will try to get to it as soon as possible

**Comment by TheAxelander** [comment]
No problem and no pressure :) Just wanted to check on that.

**Comment by Akashic101** [comment]
I was able to install the arm64-docker-image without any problems after switching from 32bit to the 64bit-version of Bullseye. While this does solve my problem it would still be great to have access to a 32bit-version if this is possible
