### ISSUE TITLE
sqlite database is not created under "/app/database"

### ISSUE THREAD

**Issue by N1c093** [TheAxelander/OpenBudgeteer#63]
Merry Christmas :)

I just installed your docker container, with sqlite database. I also added the required parameter `-e 'Connection:Provider'='sqlite'` and 
   ` -v '/my/local/path:/app/database' `
Sadly the database isn't created under `/app/database` And the folder is completely empty:

![image](https://user-images.githubusercontent.com/59510296/147414892-989c82fd-1218-4eca-bc96-4c9c672b0c37.png)

It seems like, that the database files are located directly under `/app`

![image](https://user-images.githubusercontent.com/59510296/147414873-fd3d2e9c-27fd-45c2-ae69-0d69afa50734.png)

Thank you
Nico

**Comment by TheAxelander** [comment]
Hi Nico,

you are right. I have changed the path some time ago and looks like I missed to update the documentation accordingly. So the mapping should be `-v '/my/local/path:/app'`

If I look on this now and think about it, I would say it's better to have this again under `/app/database` to separate app files and db files in the volume mapping.

I will work on that...

**Comment by curana** [comment]
I have a similar problem, but it won't create the SQLite database at all (whatever path I use). In the log it just says "Waiting for database".

Can I trigger the creation somehow?

Basically I did this:
```
docker run -d --name='openbudgeteer' \
    -e 'Connection:Provider'='sqlite' \
    -v '/my/local/path:/app/database'  \
    -p '6100:80/tcp' \
    'axelander/openbudgeteer:latest'
```

**Comment by TheAxelander** [comment]
`Connection:Provider` is no longer a valid setting and has been changed some time ago. Please use `-e 'CONNECTION_PROVIDER'='sqlite'`, more details you can find in the `README`
