### ISSUE TITLE
Move Buckets to other Bucket groups

### ISSUE THREAD

**Issue by peddarson** [TheAxelander/OpenBudgeteer#64]
Would be nice to have the possibility to move already created buckets to different groups.

**Comment by TheAxelander** [comment]
If you edit a Bucket you have an option to set the assigned Bucket Group.
![image](https://user-images.githubusercontent.com/17849665/148025533-62dc647c-662b-48bd-b577-f670f1ed41c2.png)

Is this what you are looking for?

**Comment by peddarson** [comment]
ahh, thanks. didn't see that one. 

I was looking for some sort of arrow like the one where you can rearrange the Bucket Groups.
![arrow](https://user-images.githubusercontent.com/23509891/148057780-8b188c9e-c018-4bc9-a356-5802ef106604.JPG)
