### ISSUE TITLE
Broken rule-tab if a bucket associated with a rule got deleted

### ISSUE THREAD

**Issue by peddarson** [TheAxelander/OpenBudgeteer#65]
If a rule is associated to a certain bucket and the bucket is removed/deleted the rule-tab freezes and does not show anything.
After deleting the specific rules in the database everything is back to normal.

Maybe deleting the bucket should also delete the connected rules to it?

Idk if the log helps, it is just the docker log... 
[Log OpenBugeteer.txt](https://github.com/TheAxelander/OpenBudgeteer/files/7881507/Log.OpenBugeteer.txt)

**Comment by TheAxelander** [comment]
I think I have an idea where this can happen.

Could it be possible that you have created a Bucket, then created a Rule for it and then "removed" it without assigning any Bank Transaction? If yes then I know what's the issue.

**Comment by peddarson** [comment]
> Could it be possible that you have created a Bucket, then created a Rule for it and then "removed" it without assigning any Bank Transaction? If yes then I know what's the issue.

Pretty much that's point

**Comment by TheAxelander** [comment]
Fixed with latest commit on `pre-release`
