### ISSUE TITLE
Possible Migrating from SQLite to MySQL down the line?

### ISSUE THREAD

**Issue by mardijker** [TheAxelander/OpenBudgeteer#66]
Hey, first just want to say thank you for your awesome work! I want to ask some questions, but please correct me if this is not the proper place.

I'm setting this up on my homeserver, and would it be possible if i'm using it with SQLite backend for some time, before deciding to migrate to MySQL backend later? I'm trying it for a bit, and i'm new to this stuffs.

Thank you!

**Comment by TheAxelander** [comment]
Hi there. First of all thanks a lot for your feedback. Much appreciated.

So there is no built-in DB migration implemented. 

As a first idea I would say open the database with SQLiteDatabaseBrowser and export the data (only data, not schema) as .sql file. Then use this file as Upload in phpMyAdmin. Tables in mySQL should have been already created beforehand by OpenBudgeteer.

I could image there might be some format issues between SQLite and mySQL for example with DateTime fields. So maybe then data export as CSV might be necessary to bring the data into the right format before uploading it to mySQL.

So far I never did this kind of data migration from SQLite to mySQL. Just the other way around when I started to work on SQLite compatibility and let me say it was somehow possible.

All in all my preference would be to use MySQL with the [full docker-compose](https://github.com/TheAxelander/OpenBudgeteer#docker-compose) where you have everything you need, also to manage the database itself outside of OpenBudgeteer.

**Comment by mardijker** [comment]
Ah, no problem. Thanks for the quick response. I will try the full docker-compose then.
