### ISSUE TITLE
[Docker] Add entrypoint.sh or something similar to create the initial database, user, and bootstrap the app

### ISSUE THREAD

**Issue by tvories** [TheAxelander/OpenBudgeteer#75]
It would be nice if the application automatically created the database if this was a new deployment.  I'm looking at https://github.com/psi-4ward/docker-powerdns/blob/master/entrypoint.sh as an example on how to do this. I may be able to assist here once I understand the app a bit better, but basically:

The docker container would have an entrypoint of a script and that script would bootstrap the database if it was not already present (specifically MySQL in this case).

**Comment by TheAxelander** [comment]
Now available on `pre-release`
