### ISSUE TITLE
Feature: Debit/Credit status

### ISSUE THREAD

**Issue by Peter1994** [TheAxelander/OpenBudgeteer#76]
Hi Axelander,

My bank account CSV export provides only a single field for Debits and Credits transactions. The amount in this field is always above 0. The CSV file also provides a field which describes the transaction type. The field itself is called 'Debit/credit' and contains 'Debit' or 'Credit' as values.

Is it possible to implement support for this?

**Comment by TheAxelander** [comment]
Crazy, now I realize how different banks handle these CSV exports (which is not your fault!) whishing it would be more standardized.

Overall it's possible to implement this. I think need to redesign a little bit the way how to handle these different variants of Debit and Credit values. Also referring to #72 

I will put this in my backlog for next version.

**Comment by ambroser1971** [comment]
@TheAxelander mind if I take this on this weekend? I have a similar issue with my bank.

**Comment by TheAxelander** [comment]
Sure, feel free. I haven't started working on it yet.

**Comment by TheAxelander** [comment]
Now available on `pre-release`
