### ISSUE TITLE
Unable to assign custom buckets for transactions not in current month

### ISSUE THREAD

**Issue by Zak-Bahm** [TheAxelander/OpenBudgeteer#77]
On the transactions page I'm able to assign transactions to custom bucket I make, but as soon as I go back a month they all disappear and only show the default `Income` and `Transfer` buckets. So for instance it is currently February 2022, if I click the back arrow to go to January 2022 the custom buckets I've made aren't available anymore.

**Comment by TheAxelander** [comment]
This is intended behavior of the Bucket versioning.

Once you create a new `Bucket` a new `BucketVersion` will be created with a `ValidFrom` Date starting with the current selected month. So in your case the Bucket existence starts in Feb-22 hence you will not find it in Jan-22 and earlier.

The intention is to see in the past only relevant Buckets of that time and nothing which was added in the future.

That means, select the very first month where a Bucket is required (e.g. Apr-21) and create it in this month. Then you can select it in all upcoming months until it will be set to inactive.

Does this helps?

**Comment by Zak-Bahm** [comment]
Ok, that makes more sense. And I can change this ValidFrom Date by editing "(First) Target Date:" ? Also how do I set a bucket as inactive?

**Comment by TheAxelander** [comment]
First Target Date is for Bucket Types like "Save X until Y". Right now the ValidFrom date can be only changed directly in the database. 
Setting a Bucket inactive can be done on the Page where you have created it. Just hover over it and you will see the buttons on the right side for modification and deletion. I know it's sometimes a bit glitchy when they appear/disappear.
