### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by alephtaph** [TheAxelander/OpenBudgeteer#80]
When I run the docker compose you provide, I always get an network error:

_**Deployment error**
failed to deploy a stack: Creating network "open_budgeteer_mysql-internal" with the default driver Network app-global declared as external, but could not be found. Please create the network manually using `docker network create app-global` and try again. : exit status 1_

The same happen, when I create the network manually. I use portainer to deploy my docker compose.

Thank you for any suggestions and help.

**Comment by TheAxelander** [comment]
I could reproduce this in Portainer. The internal `<stack-name>-mysql-internal` network will be created by Portainer but it looks like it cannot create the external network by himself. 
So I went into `Networks` and added `app-global` manually. After that I could deploy the stack without any error.

**Comment by dscherm55** [comment]
I had the same issue deploying via Portainer. I removed all references to the `app-global` external network from the docker-compose file and it appears to be working. Any side effects caused by not adding this network?

Thanks!

**Comment by TheAxelander** [comment]
No side effects to be expected. The `app-global` is just an example on how to handle the networks in case you are using a reverse proxy like Nginx Proxy Manager.
