### ISSUE TITLE
Using PostgreSQL?

### ISSUE THREAD

**Issue by Extarys** [TheAxelander/OpenBudgeteer#81]
Is there a way to use this with PostgreSQL? I self-host on a pi so running mutliple database servers with the other containers takes a lot of juice out of this little guy.

It seems that it cannot connect to a postgresql server no matter what I try. Prehaps someone using this had better luck and can confirm if it works and how they made it work?

Prehaps it might work in a future release with the possibility to import from the sqlite database...

I'm currently using Firefly III but although I love all the stats, I hate the way it handles budgets right now. YNAB style suits me better. <3

**Comment by TheAxelander** [comment]
PostgreSQL is currently not supported and would need to be implemented first. Can be maybe done in one of the future releases.

**Comment by Extarys** [comment]
Ok thank you for the confirmation. I'll use SQLite then :)
