### ISSUE TITLE
Cant import CSV from nationwide (UK)

### ISSUE THREAD

**Issue by Hazy87** [TheAxelander/OpenBudgeteer#82]
[Statement Download 2022-Feb-25 11-11-10.csv](https://github.com/TheAxelander/OpenBudgeteer/files/8144233/Statement.Download.2022-Feb-25.11-11-10.csv)
I have attached a csv which cant be imported as the amounts have £ at the start, this occurs when using en-GB too.

**Comment by TheAxelander** [comment]
Fixed with #83
