### ISSUE TITLE
Why isn't this secured with a login page?

### ISSUE THREAD

**Issue by BobWs** [TheAxelander/OpenBudgeteer#87]
Hi,
I was wondering why isn't your program secured with a login pag? I was testing the docker version, but I couldn't find any setting for a login pag to secure it. I mean if one using a reverse proxy with sub.domain.com and this is open to the internet everyone can see your budgeting! This in not a very secure in my opinion...

**Comment by TheAxelander** [comment]
There is already an [issue](https://github.com/TheAxelander/OpenBudgeteer/issues/9) available for this topic.
Of course I would never recommend to make OpenBudgeteer public available to the internet without any further access layer. If you already use a reverse proxy then you can also include http basic auth to this service. Or as an alternative (this is what I do) you can use [Authelia](https://www.authelia.com).
