### ISSUE TITLE
Integration in Nextcloud

### ISSUE THREAD

**Issue by natrius** [TheAxelander/OpenBudgeteer#88]
Hello, 
i read around for a bit and it seems like there are often questions about a private budget-app for Nextcloud. May it be worth to look into integrating it natively into Nextcloud?

**Comment by TheAxelander** [comment]
Will be really hard to realize this as the foundation of nextcloud is completely different and they have also separate style guidelines etc. At least from my side it's not planned to work on that in the near future.

**Comment by natrius** [comment]
I never heared about a special style guideline and I could not find anything about it in https://docs.nextcloud.com/server/latest/developer_manual/app_development/intro.html there. 

But yeah, maybe someone else could create an app and connect it with the OpenBudgeteer-Server?

**Comment by TheAxelander** [comment]
This was the one that I found after my first quick search: https://docs.nextcloud.com/server/latest/developer_manual/design/index.html
