### ISSUE TITLE
SQLite - Database is locked

### ISSUE THREAD

**Issue by N1co93** [TheAxelander/OpenBudgeteer#90]
Hello,

I just noticed a small error inside "OpenBudgeteer" with SQLite Database. If I try to bulk edit the transactions (button "edit all") and save all, the following error appears.

![image](https://user-images.githubusercontent.com/59510296/159014483-714ce19a-4e09-4f0f-9161-f149662c33f3.png)

As a workaround I can edit one row after each other. This is working fine.

Thank you
Nico

**Comment by TheAxelander** [comment]
Hello Nico, I will try to reproduce this. Can you tell how many transactions you wanted to edit at once?

**Comment by tibuski** [comment]
Hello,

I just had the same issue with 250 transactions.
I create a rule with contains : christ et vic
Go to transactions, propose bucket, it propose bucket with chris et vic for +- 10 records, save all and the issue appears.

Docker with SQL Lite.

**Comment by N1co93** [comment]
@TheAxelander I try to edit some transactions (around 5) from month March. There are currently 45 transactions in march. Do OpenBudgeteer save every transaction, even if I only edit 5 rows?

**Comment by TheAxelander** [comment]
Only transactions which are in modification mode (meaning you see Input Boxes for them) will be considered during save action. So if you only modify 5 rows then only these 5 will be processed.

I was able to reproduce this behavior. I can imagine it has something to do with the parallel processing which would then surprisingly only happens on Sqlite databases. I thought I covered these kind of database locks, let's see what I can find out.

**Comment by TheAxelander** [comment]
I found the root cause. Sqlite can only handle one single db-transaction for commit or rollback actions. If you save multiple bank transactions then OpenBudgeteer creates one db-transaction overall and then a db-transaction per row (containing bank transaction changes and bucket assignments).

I think I can fix this quite quickly.

**Comment by TheAxelander** [comment]
Fixed with 8687ca1c344908e71259d5ec14cf0691094de0a4
