### ISSUE TITLE
April with OpenBudgeteer - Can't set initial balance

### ISSUE THREAD

**Issue by Extarys** [TheAxelander/OpenBudgeteer#92]
For the new month I wanted to give this a try coming from Firefly III. I'll miss some features, but I miss the "assign each dollar to a task" type of thinking more.

I created my main account and my credit card account. I had some issues creating the initial balance transaction with my main account but it eventually worked. With my credit card, it doesn't. I have "Amount between Bucket assignment and Transaction not consistent.".

I tried with "Transfer", "Income" and "No selection", with various dates (yesterday, today), on the left number field and the right number field... I had the same issue with my bank account and the number was positive, now I have this issue with a negative value - not sure how that could play a role here.

![image](https://user-images.githubusercontent.com/11581433/161127561-30519789-fd68-4437-88a8-758baeea250a.png)

How can I fix this? :smile: thank you!

And how do I manage buckets for paying debts? What is the common way of doing this?

**Comment by TheAxelander** [comment]
Best practice would be to create an initial Transaction mark it as "Income". Please note that the amount on the right and left side are equal. The error occurs if this is not the case.

**Comment by Extarys** [comment]
Ohhhhhhh thank you! I wasn't sure what the right input field was for :smile:
