### ISSUE TITLE
Request: provide Dockerfile used to build images on dockerhub

### ISSUE THREAD

**Issue by senorsmile** [TheAxelander/OpenBudgeteer#94]
It would be great to see the Dockerfile used to build those images.  I would expect to see it here in the project repo.  
For the security minded, it's never a bad idea to rebuild the images oneself after inspecting the Dockerfile and other code to have complete understanding.

**Comment by TheAxelander** [comment]
The Dockerfile can be found in folder OpenBudgeteer.Blazor
