### ISSUE TITLE
Login for multiple users

### ISSUE THREAD

**Issue by charyouz** [TheAxelander/OpenBudgeteer#95]
Is there a plan to get multiple users on the platform?
For instance a family where each member would have their own account and not be able to see each others budgets? Or as a setting to have limited/full visibility but not be able to modify the budgets?
I think this is nice, but I don't want my budget to be visible to anyone who is in my wlan network at least without any passwords.

**Comment by TheAxelander** [comment]
Having a Login is overall planned with #9 but not for multiple users. My recommendation would be to run multiple instances of the docker container where everybody has it's own site and backend database.

In the meantime I also recommend login procedures via Nginx Proxy Manager (HTTP Auth) or Authelia.
