### ISSUE TITLE
Bucket In value not calculating correctly

### ISSUE THREAD

**Issue by charyouz** [TheAxelander/OpenBudgeteer#96]
If I by accident add too much to a bucket, I can remove money from it by adding a negative value.
This however does not change the value "In"

Is there any way to reset all transactions done to a bucket? Or

**Comment by TheAxelander** [comment]
"In" value only contains money that was put into the Bucket. If you take money out, it will be summarized by the "Out" value.

Resetting Bucket Movements is only possible via database manipulation which is overall not recommended to keep data consistency.
