### ISSUE TITLE
Add total Want for each bucket

### ISSUE THREAD

**Issue by charyouz** [TheAxelander/OpenBudgeteer#99]
I think it would be a good idea to have each bucket show the total Want that is left for the month.
For instance I have certain buckets that accrue balance for a year and they I pay the bills from them. I move money each month to the buckets and I like to move the total sum instead of doing many small transactions.
It would be nice to know the total sum that the bucket needs.

**Comment by TheAxelander** [comment]
Hey, I'm not sure if I got it right. So for your Use Case what kind of Bucket Type you would use. Depending on that the expected Want for the month will be calculated. 

To give some examples:
On monthly base: Want = Target
On Save 30€ until Oct-22: Want = Remaining Amount / Remaining Months

**Comment by charyouz** [comment]
So I have a bucket group that has buckets consisting of (mostly) Expense every X months buckets.
I then created an account for these expenses and move money there every month.

Currently I sum up the Want every month and move that amount to the account.

The suggestion is to add the total wants of each bucket group the same way that the Balance is displayed for each bucket group.

This way I could instantly see how much money is needed to be moved each month instead of summing them up myself.

**Comment by TheAxelander** [comment]
Ahh on Bucket Group level. Now I got it. Thanks. Point taken.

**Comment by TheAxelander** [comment]
Now available on `pre-release`
